name: Dynamic Test

on:
  workflow_dispatch:

jobs:
  set_environment_runner:
    outputs:
      env: ${{ steps.setenv.outputs.env }}
      runner: ${{ steps.setenv.outputs.runner }}
    runs-on: self-hosted
    steps:
      - id: setenv
        run: |
          echo "::set-output name=env::main-env"
          echo "::set-output name=runner::self-hosted"
  migrate:
    runs-on: self-hosted
    needs: set_environment_runner
    environment:
      name: ${{ needs.set_environment_runner.outputs.env }}
    steps:
      - name: Create and activate virtual environment
        run: |
          source_env="${{ env.env }}"
          echo "$source_env"
