name: Dynamic Test

on:
  workflow_dispatch:

jobs:
  set_environment_runner:
    outputs:
      env: ${{ steps.setenv.outputs.env }}
      runner: ${{ steps.setenv.outputs.runner }}
    runs-on: self-hosted
    steps:
      - id: setenv
        run: |
          echo "env=main-env" >> $GITHUB_ENV
          echo "runner=self-hosted" >> $GITHUB_ENV

  migrate:
    runs-on: self-hosted
    needs: set_environment_runner
    environment:
      name: ${{ needs.set_environment_runner.outputs.env }}
    steps:
      - name: Create and activate virtual environment
        run: |
          source_env="${{ vars.env }}"
          echo "$source_env"
